### ISSUE TITLE
Requested feature: Ability to collect all distinct values for a given node/path 

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/Argonodes#19]
idea would be that after you have your tree you could do something like

`tree.scanForDistinctValuesAtPath(path)`
or `node.scanForDistinctValues()`

which would hold in memory against that node in the tree, the list of possible values.

(implies you can get it later e.g. 
`node.getFoundValues()`
or `tree.getFoundValuesAtPath(path)`

Nice to have:

- features/examples scripts to view the lists of found values for different node paths in human friendly table, like you did with descriptions. 

There are follow on feature ideas from this, but I will put them in separate tickets and link back to this one.

A few further notes:
- this should remove duplicates, so you only collect distinct values
- maybe alpha sort values for convenience?
- keep case of text exactly as found
- don't limit this to recurring values, find everything but maybe have a way to distinguish recurring values from one-off values? 
- There are two motivations for collecting found values:
  (i) to help us enumerate the closed set of possible values for a given field.
  (ii) to collect sample data for use in mockups, visualisations etc.
  At this stage, I don't think we need to differentiate between them, though to achieve the abilities of cutting / separating them these issues become important:
     - #21
     - #22
     - #23

**Comment by Amustache** [comment]
- [ ] Main feature
- [ ] Hold in memory
- [ ] Can retrieve values
- [ ] "features/examples scripts to view the lists of found values for different node paths in human friendly table, like you did with descriptions."
- [ ] "this should remove duplicates, so you only collect distinct values"
- [ ] "maybe alpha sort values for convenience?"
- [ ] "keep case of text exactly as found"
- [ ] "don't limit this to recurring values, find everything but maybe have a way to distinguish recurring values from one-off values?"
