### ISSUE TITLE
Psst. Shoudn't it be a Discussion instead?

### ISSUE THREAD

**Issue by Amustache** [hestiaAI/Argonodes#61]
Before opening a new issue, ask yourself whether it is something concrete or abstract.

Does your thinking stem from a feature that doesn't work? A broken piece of code? A missing feature? A concrete idea of what the package should do? Then open a [new issue](https://github.com/hestiaAI/Argonodes/issues/new)!

Is your reflection on the uses of the package? On the definition of concepts? On the terms to use? Then open a [new discussion](https://github.com/hestiaAI/Argonodes/discussions/new)!

**Comment by pdehaye** [comment]
It feels pretty abstract to me!
