### ISSUE TITLE
Parser: ZIP (multifiles)

### ISSUE THREAD

**Issue by Amustache** [hestiaAI/Argonodes#69]

**Comment by Amustache** [comment]
How should it be used?

1. You put an archive in a **[generic? specialized?]** Parser, and this Parser gives the list of available files in the ZIP.
2. The user selects the files to be processed/considered.
3. The user also associates a File Parser if necessary (e.g., CSV>JSON).
4. For each file, a **[Tree? Model?]** is associated.
5. When finished, the export proposes **[a common Model? one Model per file?]**.

Questions are **[between brackets]**.

**Comment by pdehaye** [comment]
6. Options to transfer it to the Hugo Semantization bubble?

All sound like good ideas.

**Comment by Amustache** [comment]
For the record:

> 1. You put an archive in a **[generic? specialized?]** Parser

   **I did a generic ZIP Parser, that takes as an argument a specific Parser for the tiles.**

> 4. For each file, a **[Tree? Model?]** is associated.

**For each file, a Tree is associated.**

> 5. When finished, the export proposes **[a common Model? one Model per file?]**.

**You can choose, but my way is "a Model for all Trees".**
